<?php
/**
 * backfill_practice_code.php
 * ─────────────────────────────────────────────────────────────────────────────
 * Preview & apply matching of 2026 Dropbox folders → requests.practice_code
 *
 * Logic
 *   1. Load the 1178 2026 folder names (embedded array below).
 *   2. Query requests where practice_code IS NULL or '' and status = 'Inquiry'.
 *   3. For each request, try to find a matching folder:
 *        a) Exact  : normalize(folder_customer) == normalize(request.customer_name)
 *        b) Starts-with: folder_customer starts with normalize(request_name) (min 5 chars)
 *        c) Contains   : normalize(folder_customer) contains normalize(request_name) (min 5 chars)
 *      "normalize" = lowercase + strip all non-alphanumeric chars
 *   4. Show a preview table — one row per request with suggested folder.
 *      Multiple folder matches flagged as AMBIGUOUS (shown but pre-unchecked).
 *   5. POST with checked rows → UPDATE requests SET practice_code = ? WHERE id = ?
 *
 * Deploy to hub root or /modules/leads/  — uses the hub config/db helpers.
 * ─────────────────────────────────────────────────────────────────────────────
 */

require_once __DIR__ . '/includes/config.php';
require_once __DIR__ . '/includes/auth.php';
require_once __DIR__ . '/includes/db.php';
require_permission('admin');   // admin/manager only

// hub includes/db.php creates $pdo but no db() function — add it here
if (!function_exists('db')) {
    function db(): PDO { global $pdo; return $pdo; }
}

// ── Embedded folder list (2026) ───────────────────────────────────────────────
$folders2026 = [
    '03Persons(BTG-Micky)',
    '10PaxGroup(KendiritaTours-Micky)',
    '2ClientsRequirement(LuxuryUnlocked-Micky)',
    '2paxJune(KendiritaToursandTravel-Micky)',
    '3paxjuly(Sultan-GDS)',
    '4nightZnz(BTG-Micky)',
    '6DAYSTANZANIASAFARIPACKAGE',
    '6DegreeTravel(Roberto)',
    '6nights(BTG-Micky)',
    'Abaurre(Patricia-Agustin)',
    'AdellaBacci(Alessia)',
    'Aden(Sultan-Drct)',
    'Adit(Micky-Drct)',
    'AdnanTayebjeeI(Micky-Drct)',
    'Adriana(Agustin-Drct)',
    'Adriana(Nuru)',
    'AdrianaBenedetti(Sultan-Drct)',
    'AdrianaCarbone(Anderson)',
    'AgataLazzoni(Alessia)',
    'Aida(EncounterAfricaSafaris-Micky)',
    'AideSmithers(Micky-Drct)',
    'Akila(BTG-Micky)',
    'AlaaMneizel(Nuru)',
    'Alberto(Sultan-Drct)',
    'AlbertoBagnacani(Sara)',
    'AlbertoLolivieri(Capri)',
    'AlbertoRossi(Daniela)',
    'AldoFedeli(Alex)',
    'Alejandro(Sultan-Drct)',
    'AleksandarAlex(Sultan-Drct)',
    'Alessandra(ToursoleblusiciliaDaniela)',
    'AlessandraChiusano(Capri)',
    'AlessandraDeAngelis(Anderson)',
    'AlessandraDeStefano(Daniela)',
    'AlessandraMorandi(Capri)',
    'AlessandraTezza(Sultan-Drct)',
    'Alessandro(Sultan-Drct)',
    'AlessandroAlberti(Anderson)',
    'AlessandroBevilacqua(Anderson)',
    'AlessandroCastiglioni(Daniela)',
    'AlessandroDellaRovere(Anderson)',
    'AlessandroGardin(Anderson)',
    'AlessandroMalvone(Sultan-Drct)',
    'AlessandroMariucci(Anderson)',
    'AlessandroPiane(Sultan-Drct)',
    'AlessandroRapali(Agustin-Drct)',
    'AlessandroRapali(Alessia-Drct)',
    'AlessandroSallustri(HTSViaggi-Daniela)',
    'AlessandroVolonterio9Sultan-Drct)',
    'Alessia(AlessiaAdventure-Daniela)',
    'AlessiaCapra(Anderson)',
    'AlessiaDapra(Roberto)',
    'AlessiaMarengo(Nuru)',
    'AlessiaNero(Capri)',
    'AlessiaPettina(PettinaViaggi-Daniela-KENYA)',
    'AlessiaPiantoni(Roberto)',
    'AlessiaViscardi(Micky-Drct)',
    'AlessiaZavaresi(Alessia)',
    'AlessiaZavarise(Alessia)',
    'AlexWat(Agustin-Drct)',
    'AlfonsoSantiagoMaruccoSantos(Sultan-SB)',
    'Alfred(Roberto-Drct)',
    'Algostino(Lamiafrica-Roberto)',
    'Ali(Sultan-Drct)',
    'Alice(Agustin-Drct)',
    'AliceAndPaki(Micky-Drct)',
    'AliceBestetti(Anderson)',
    'AliceParisotto(Alessia)',
    'AlonBartal(Agustin-Drct)',
    'AlwiyahMasbah(Agustin-SB)',
    'AmedeoBaiamonte(Rick)',
    'Amelia(Nuru-Drct)',
    'AmyFranklin(Sultan-SB)',
    'Ananya(BTG-Micky)',
    'AnaVojvodic(Agustin-Drct)',
    'Andrea(Nuru-Drct)',
    'AndreaAmbrosini(Daniela)',
    'AndreaAnedda(Nuru)',
    'AndreaArca(Nuru)',
    'AndreaBaglioni(Sara)',
    'AndreaBosisio(Roberto-Drct)',
    'AndreaCentini(Anderson)',
    'AndreaGilioli(Capri)',
    'AndreaMaffei(Anderson)',
    'AndreaNesti(Sultan-Drct)',
    'AndreaParoni(Anderson-Drct)',
    'AndreaRegalia(Capri)',
    'AndreaRodono(Nuru-EleonoraOngaro)',
    'AndreaSartori(Alessia)',
    'AndreaScrivo(Anderson)',
    'AndreaSoldini(Anderson)',
    'AndreaVignoni(Sultan-Drct)',
    'AndreeaGavrilescu(TrafficadidiViaggio-PS-Daniela-Kenya)',
    'AndresDuque(Micky-Drct)',
    'AndresReatiga(Micky-SB)',
    'AndrewNeo(Agustin-SB)',
    'Angela(Sultan-Drct)',
    'AngelaDonofrio(Roberto)',
    'AngelikaBreuss-Kaufmann(Micky-Drct)',
    'AnginetteMacKinnon(Micky-SB)',
    'Anjali(Agustin-Drct)',
    'Anna(Anderson)',
    'AnnaBrunello(Anderson)',
    'AnnaCanavero(Rick)',
    'AnnalisaAlloca(Anderson)',
    'AnnalisaPuca(Anderson)',
    'AnnalisaRusso(Alessia-Drct)',
    'AnnaPellegrini(Rick)',
    'AnneMarie(Sultan-Drct)',
    'AnotherGlobeViaggi(Sara)',
    'Antolog(Eko-Roberto)',
    'Antonella(Nuru-Drct)',
    'AntonellaElisa(Alessia)',
    'AntonellaIndelicato(Alessia)',
    'AntoniettaFragnito(Anderson)',
    'Antonio(Cimoservice-Nuru)',
    'AntonioD¡Domenicantonio2(Anderson)',
    'AntonioMagno(Sara)',
    'AntonioNeglia(Capri)',
    'AntonioTaioli(Sultan-Drct)',
    'AprilLi(Agustin-SB)',
    'AprilSafari(BTG-Micky)',
    'AriannaChino(Alessia-Drct)',
    'AriannaGoWorldMikumi(GoWorld_Alex)',
    'AriannaPoli(Capri)',
    'AriannaSmeraldo(Daniela)',
    'ArnaudLadame(Agustin-Drct)',
    'ArthurHastert(Micky-SB)',
    'AshleyBiordi(Agustin-SB)',
    'Ashok(Agustin-Drct)',
    'Aug26(64Travel-Roberto)',
    'August(KendiritaTours-Micky)',
    'AuroraCondoluci(Sultan-Drct)',
    'BaileMoore(Micky-Drct)',
    'BananaTours(Adele-Drct)',
    'Bartolomeo(Sultan-Drct)',
    'Bassano(GoWorld-Roberto)',
    'Bassi(AvventureEsotiche-PS-Roberto)',
    'BeatriceFiumi(Agustin-Drct)',
    'BeatricePagliughi(Sultan-Drct)',
    'Becky(Agustin-Drct)',
    'Becky(Micky-Drct)',
    'Belinda(Agustin-Drct)',
    'Benedetti(Cimoservice-Roberto)',
    'BenjaminPooley(Samwel-SB)',
    'Bernardi(Sultan-Drct)',
    'BestofTanzani(KendiritaTours-Micky)',
    'BibianaMaffi(Sultan-Drct)',
    'Boaz(Micky-Drct)',
    'Borri(SouriTrip-Roberto)',
    'Branchini(VolaEVa-Roberto)',
    'BrandonPang(Micky-Drct)',
    'Bravo(Africanguide-Roberto)',
    'BrendaSwidzinski(Agustin-Drct)',
    'Brigoli(Daniela-UGANDA)',
    'BruceLepolstat(Micky-SB)',
    'BuscaginMatteo(Capri)',
    'Cacace(Avventure-PS-Roberto)',
    'Caccioppola(Lamiafrica-Roberto)',
    'CalabrettiMariaTeres(Alessia)',
    'Calisi(Verticalife-Roberto)',
    'CalvinChao(Agustin-Drct)',
    'CamillaBonci(Nuru-Drct)',
    'CamillaGarritano(Sara)',
    'CarlaFerrero(Roberto)',
    'Carlo(SenzaFrontiere-Daniela)',
    'Carlo90(Anderson)',
    'CarloGRP(Kailas_Alex)',
    'CarloLazzaro(Sultan-Drct)',
    'CarloRinaldi(Sultan-Drct)',
    'CarlottaCassan(Sultan-Drct)',
    'CarlottaColombo(Sultan-SB)',
    'CarlottaMeroni(Nuru)',
    'CarmeloBarone(Alessia)',
    'CarolHanson(Agustin-SB)',
    'Caroline(Agustin-Drct)',
    'CarolZhao(Agustin-SB)',
    'CatherineDeKock(Agustin-Drct)',
    'CatherineKrueger(Samwel-SB)',
    'CeciliaBorrani(Anderson)',
    'CelesteMicalizzi(Anderson)',
    'CharitaBoserman(Anderson)',
    'CharlesHartford(Agustin-Drct)',
    'CharliePearson(Micky-Drct)',
    'ChenCa(Agustin-SB)',
    'CherylPottruff(Agustin-Drct)',
    'Chiara(Nuru-Drct)',
    'Chiara(Sultan-Drct)',
    'ChiaraAbbasciano(Anderson)',
    'ChiaraAlbanese(Nuru)',
    'ChiaraBologna(Sara)',
    'ChiaraCannone(Nuru-EleonoraOngaro)',
    'ChiaraCesello(Sultan-Drct)',
    'ChiaraGariglietto(Nuru)',
    'ChiaraLambrughi(Sultan-Drct)',
    'ChiaraNiccolai(Nuru-Trekk)',
    'ChiaraPanse(Anderson)',
    'ChiaraPilati(Alessia)',
    'ChiaraViganoi(Sultan-Drct)',
    'ChinnapongRuvijacharakul(SagaExpedition-Micky)',
    'Chloe(Samwel-Drct)',
    'ChloePogrebniak(Adele-Drct)',
    'Christian(Adele-Drct)',
    'ChristianGrimacchia(InnViaggi-Daniela-KENYA)',
    'ChristianHernandez(Agustin-SB)',
    'Chutima(SagaExpedition-Micky)',
    'Ciara(Sultan-Drct)',
    'Cintia(Sultan-Drct)',
    'CinziaSolarino(Nuru-Drct)',
    'Claudia(Anderson)',
    'ClaudiaCiarelli(Rick)',
    'ClaudiaMasiero(Anderson)',
    'ClaudiaMatassoni(Roberto)',
    'ClaudiaMerlo(Viagginuovaera-PS-Daniela-KENYA)',
    'ClaudiaRizzi(Sara)',
    'ClaudioRossetti(Anderson)',
    'ClaudioRuvo(D\'IstintiViaggi-Daniela)',
    'ClaudioSalma(Anderson)',
    'CleoLi(Agustin-Drct)',
    'ClientRequirement(LuxuryUnlocked-Micky)',
    'Coglitore(CimoService-Roberto)',
    'Costanza(SouriTip)_Alessia',
    'CristensJespers(Micky-Drct)',
    'CristianaVillani(Anderson)',
    'CristinaFichera(Sara)',
    'CristinaFichera2(Sara)',
    'CristinaGuarino(Anderson)',
    'CristinaPirazzoli(Nuru-Trek)',
    'DamienBenney(Agustin-SB)',
    'DanhuiChen(Agustin-SB)',
    'Daniel(Micky-Drct)',
    'DanielaBerettini(Alessia)',
    'DanielaHurtado(Micky-Drct)',
    'DanielaModafferi(Daniela)',
    'DanielaPennone(Anderson)',
    'DanielaScarpa(Anderson-Drct)',
    'DanielaTorres(Capri)',
    'DanieleCamerota(GodoTravel-LAM-Daniela)',
    'DanieleMango(Alessia)',
    'DanielJAberle(Sultan-SB)',
    'Danilo(Anderson)',
    'DaniloPozzi(Anderson)',
    'DanyuSong(Agustin-SB)',
    'Dario1971(Anderson)',
    'DarioCapineri(Anderson)',
    'DarioFerrara(Capri-EleonoraOngaro)',
    'DarioManchart(Sultan-Drct)',
    'DariushYazdani(Sultan-SB)',
    'Dattero(Sultan-Drct)',
    'David(Agustin-Drct)',
    'David2(Agustin-Drct)',
    'DavideBucalo(Nuru-Drct)',
    'DavideCatasta(Anderson)',
    'DavideCiarlo(Sara)',
    'DavideDalDosso(Sara)',
    'DavideMattis(Sara)',
    'DavideNegri(Anderson)',
    'DavideRebeccato(Nuru-Trekk)',
    'DavideRecalegari(Nuru)',
    'DeboraDagostino(Eko-Roberto)',
    'DEC(Sultan-GDSTravels)',
    'DeMartino(SouriTrip)_Alessia',
    'DeniseLuzzi(Alessia)',
    'DerekLaidlaw(Agustin-SB)',
    'DeryaSargin(Micky-SB)',
    'DeStefano(Africando-Daniela)',
    'DestinationSerengeti(BTG-Micky)',
    'Destinova(BTG-Micky)',
    'DhimantDoshi(Agustin-Drct)',
    'DianeValentino(Micky-SB)',
    'DiegoCarron(TravelEmotionDesign-PS-Daniela-KENYA)',
    'DOIT(Doit-PS-Roberto)',
    'DomenicoQuarto(Anderson)',
    'DominicGranter(Sultan-Drct)',
    'DonaldPrazuch(Agustin-Drct)',
    'DongYang(Agustin-Drct)',
    'DoreenCody(Sultan-SB)',
    'Dorit(Sultan-Yeadimtravel)',
    'DouglasSelkirk(Sultan-SB)',
    'DuanShuyue(Agustin-SB)',
    'Duma(RaccontiDiViaggio-Roberto)',
    'Duma(UnEmozionePerSempre-PS-Roberto)',
    'Edoardo(Sultan-Drct)',
    'EdoardoDaminato(Roberto)',
    'EdoardoSacca(Nuru-Drct)',
    'EduardoGarza(Micky-Drct)',
    'Elaine(Agustin-Drct)',
    'ElaineIrias(Agustin-SB)',
    'ElenaDelSal(Sultan-Drct)',
    'ElenaMoffa(Anderson)',
    'ElenaPedol(Capri-EleonoraOngaro)',
    'ElenaPerfetti(Euphemia-PS-Roberto)',
    'ElenaRadonicich(Anderson)',
    'ElenaSanneris(Sultan-Drct)',
    'Eleonora(Sultan-Drct)',
    'Eleonorac(Sultan-Drct)',
    'EleonoraCappelli(Capri)',
    'EleonoraFulvimari(Rick)',
    'EleonoraMaggi(Roberto)',
    'EleonoraMontani(Capri)',
    'EleonoraOlia(Capri)',
    'ElianaNascimento(Sultan-Drct)',
    'ElianaNascimiento(Roberto)',
    'Elisa(Sultan-Drct)',
    'ElisaActis(Micky-Drct)',
    'ElisabettaBargagna(Astisrl-PS-Daniela-KENYA)',
    'ElisabettaLippi(Anderson)',
    'ElisaBonomi(Roberto)',
    'ElisaDutti(Africaland-Roberto)',
    'ElisaFarella(Anderson)',
    'ElisaMazara(Sultan-Drct)',
    'ElisaRossetti(Anderson)',
    'ElisaSandron(Anderson)',
    'ElisaTognetti(Anderson)',
    'ElisGarcia(Agustin-Drct)',
    'ElizabethMinnie(Agustin-Drct)',
    'ElizaZacharia(Micky-Drct)',
    'Elva(EncounterAfrica-Micky)',
    'Emanuela(Daniela)',
    'EmanuelePederiva(Sultan-Drct)',
    'EmanuelePiunti(Movimondo-Daniela)',
    'EmilianoAlfa(Alessia)',
    'Emily(Agustin-Drct)',
    'EmmaHall(Micky-Drct)',
    'EmmanueleMezzeo(Anderson)',
    'EnricaDeBellis(Anderson)',
    'EnricaD\'Arcangelo(Nuru-Trekk)',
    'EnricaMazzelli(Nuru-Drct)',
    'EnricoMazzucca(HTSViaggi-Daniela)',
    'EnricoZoccatelli(Anderson)',
    'EricaCoradeschi(Capri)',
    'EricaKronheim(Agustin-Drct)',
    'EricaPiubelli(Alex)',
    'EricRumery(Micky-Drct)',
    'ErikaBolla(Sultan-Drct)',
    'ErikaSandri(Sara)',
    'EstefanySocarro(Samwel-Drct)',
    'EthanWaul(Agustin-Drct)',
    'Eugenia(Federica_Kailas_Alex)',
    'EugenioPompilioDonadio(Daniela)',
    'Evangelia(Anderson)',
    'EverettEugenePhlipot(Micky-SB)',
    'EvgeniyaStrelnikova(Anderson)',
    'Fabiana(AvventureEsotiche-PS-Daniela-UGANDA)',
    'Fabio(Anderson)',
    'FabioBonatto(Anderson)',
    'FabioBorgia(Daniela)',
    'FabioFieni(Capri)',
    'FabioGiansante(Anderson)',
    'FabioGrossi(Sultan-Drct)',
    'FabiolaMulazzi(Anderson)',
    'FabrizioBariselli(lessia)',
    'FabrizioFabbrini(Capri)',
    'FabrizioGuerrini(CGTravel-Daniela)',
    'FabrizioPolinelli(Teloni-Roberto)',
    'FaruSpecial(Amisano-Roberto)',
    'FEB1(Sultan-Drct)',
    'Feb27(MaxTravel-Roberto)',
    'Fedemitica(Anderson)',
    'Federica(Anderson)',
    'Federica(Sultan-Drct)',
    'FedericaBergonzini(VadoalMassimo-Daniela-KENYA)',
    'FedericaBianco(Sultan-Drct)',
    'FedericaCapelli(Sultan-Drct)',
    'FedericaCatena(Nuru)',
    'FedericaColombo(Nuru)',
    'FedericaCrippa(Anderson)',
    'FedericaNuzzo(Sultan-Drct)',
    'FedericaPichierri(Daniela)',
    'FedericaS(Sultan-Drct)',
    'FedericaSilveri(Anderson)',
    'FedericoArquilla(Nuru-Drct)',
    'FedericoBoni(Roberto)',
    'FedericoCosta(Sultan-Drct)',
    'FedericoGuidetti(Alessia)',
    'FedericoMeraviglia(Nuru)',
    'FedericoMisticoni(Sultan-Drct)',
    'FedericoRega(BoghiViaggi-Daniela-KENYA)',
    'FelixGarcia(Adele-Drct)',
    'Fernanda(Agustin-Drct)',
    'Fernando(Anderson)',
    'FilippoCavallero(Capri-EleonoraOngaro)',
    'FiorenzaBiancini(Anderson)',
    'FlaminiaGarozzoi(Nuru-Drct)',
    'Flavia(Sultan-Drct)',
    'FlaviaBetti(Daniela)',
    'FlaviaCagnetti(Nuru)',
    'Fran(Sultan-Drct)',
    'FrancaPerotto(Anderson)',
    'Francesca(Alessia)',
    'FrancescaAntonelli(Sara)',
    'FrancescaCazzani(Anderson)',
    'FrancescaCostagliola(Anderson)',
    'FrancescaCozzi(Alessia)',
    'FrancescaCozzi(lessia)',
    'FrancescaCuozzo(Nuru-Trek)',
    'FrancescaGiancola(Nuru-Drct)',
    'FrancescaLunati(Gate65-PS-Daniela-KENYA',
    'FrancescaMalfronte(Alessia)',
    'FrancescaMasi(Anderson)',
    'FrancescaMonteverde(Sultan-Drct)',
    'FrancescaMonticone(Capri)',
    'FrancescaNatangeli(Anderson)',
    'FrancescaPiancastelli(Sultan-Drct)',
    'FrancescaRadin(Sultan-Drct)',
    'FrancescaRomanini(Roberto)',
    'FrancescaScabbio(Anderson)',
    'FrancescaSestilli(Nuru-Drct)',
    'FrancescaTagli(Alessia)',
    'FrancescoBorg(Sultan-Drct)',
    'FrancescoCappotto(Anderson)',
    'FrancescoCianCiulli(Sultan-Drct)',
    'FrancescoDelCorte(IoViaggioResponsabile-LAM-Daniela-MAD)',
    'FrancescoEsposito(Nuru)',
    'FrancescoPasquini(Anderson)',
    'FrancescoSabatelli(Nuru-Trekk)',
    'FrancescoSalmoiraghi(Daniela-UGANDA)',
    'FrancescoValletta(Roberto)',
    'FrancoGiardino(Sultan-Drct)',
    'Frigerio(TourandTour-PS-Daniela-KENYA)',
    'Gabriele(Nuru-Trekk)',
    'GabrieleDiCinto(Alessia)',
    'GabrieleSimonetti(Sultan-Drct)',
    'GabrioGiorcelli(Micky-Drct)',
    'GaiaNostran(Alessia)',
    'Galligani(AstiSRL-PS-Daniela-KENYA)',
    'GarbinLaura(Anderson)',
    'GelsominaPagliaro(Capri-EleonoraOngaro)',
    'GeorgiAnja(Agustin-SB)',
    'Ghilotti(Africando-Daniela)',
    'GiadaCimarosti(Anderson)',
    'GiadaRosselli(Alessia)',
    'GiadaSoldano(Avantitutta-PS-Daniela)',
    'GiadaZanfanti(AvventureEsotiche-PS-Nuru)',
    'GiangiacomoRocco(Lamiafrica-Roberto)',
    'GianlucaDimieri(Alessia)',
    'GianlucaMarch(Sultan-Drct)',
    'GianlucaNovaresi(Sultan-Drct)',
    'GianlucaPaparella(AuroraViaggi-LAM-Daniela)',
    'GianPaoloColucci(Anderson)',
    'GinaGurgoglione(Alessia)',
    'GinevraGirotto(Anderson)',
    'GiorgiaAmato(Nuru)',
    'GiorgiaBisi(Sultan-Drct)',
    'GiorgiaCaizza(Sultan-Drct)',
    'GiorgiaGaviano(Anderson)',
    'GiorgiaLevati(Anderson)',
    'GiorgiaMonibidin(QuarzoViaggi-PS-UGANDA)',
    'GiorgiaSardelli(Alessia)',
    'GiorgiaVendegna(MargitWaldschmidt-LAMDaniela-KENYA)',
    'GiorgiodiFabio(Alessia)',
    'GiorgioMazzarella(Capri-EleonoraOngaro)',
    'GiovannaBrunelli(IreneViaggi-PS-Daniela)',
    'GiovannaDevizzi(TrafficantidiViaggi-PS-Daniela)',
    'GiovannaPolleri(Nuru-Drct)',
    'GiovanniBuglioneCeresai(Anderson)',
    'GiovanniCioni(Ioviaggioresponsabile-LAM-Daniela)',
    'GiovanniFenati(Alessia)',
    'GiovanniGrassi(Nuru-Drct)',
    'GiovanniMaggiorai(Anderson)',
    'GiovanniMorini(Sultan-Drct)',
    'GiudittaAnastasio(Nuru)',
    'Giulia(MondoOverland-Daniela)',
    'GiuliaAlessandri(Sultan-Drct)',
    'GiuliaBobba(Alessia)',
    'GiuliaBoschi(Capri)',
    'GiuliaBrusa(Anderson)',
    'GiuliaCicchetti(Roberto)',
    'GiuliaDegano(Anderson)',
    'GiuliaDeibianchi(Anderson)',
    'GiuliaGermani(Sultan-Drct)',
    'GiuliaMonteleone(TrafficantidiViaggi-PS-Daniela)',
    'GiulianaDeFalco(Sultan-Drct)',
    'GiuliaPeregoi(Sultan-Drct)',
    'GiuliaPisani(Sultan-Drct)',
    'Giuseppe(Sultan-Drct)',
    'GiuseppeDiPaola(Sara)',
    'GiuseppeFerrari(Capri)',
    'GiuseppeMariaBosco(Nuru)',
    'GiuseppinaCacciola(TrafficantidiViaggi-PS-Daniela)',
    'Giusi(Nuru-trek)',
    'Gloria(Nuru)',
    'Gopihope(Micky-Drct)',
    'GraemejMorley(Agustin-Agustin)',
    'GranSafari(ComeTiPiaceViaggi-Roberto)',
    'Graziana(Sultan-Drct)',
    'Grech(Sultan-Drct)',
    'GreggMonastiero(Micky-Drct)',
    'GretaLippi(Roberto)',
    'Grethel(Sultan-Drct)',
    'Groupsize4(WOA-Micky)',
    'GRUPPI-Domenica(Roberto)',
    'GRUPPI-Giovedi(Roberto)',
    'GruppoKenya(LaTimpaTravel-PS-Daniela-KENYA)',
    'GSPemba(Daver-PS-Roberto)',
    'GuadalupaViaggi(GoWorld-Roberto)',
    'Guillaume(Micky-Drct)',
    'Guo(Agustin-Drct)',
    'GuyaAllodi(Alessia)',
    'HadiaAyub(Micky-Drct))',
    'Halannakwiatkowksi(Agustin-Drct)',
    'Hana(Agustin-Drct)',
    'Hannah(Agustin-Drct)',
    'HaoranCheng(Agustin-Drct)',
    'HardianaMahmood(Agustin-SB)',
    'HassaanShafqat(Micky-SB)',
    'HeinrichKlingner(Micky-SB)',
    'HilaParty(Sultan-Yeadimtravel)',
    'HildeHammerRognehaug(Agustin-Drct)',
    'Himanshu(BTG-Micky)',
    'Hirel(Agustin-Drct)',
    'HoneymoonCouple(Agustin-Patricia)',
    'HoneymoonCouple(BTG-Micky)',
    'Honeymooners(Euphemia-PS-Roberto)',
    'Honeymooners(KadmarTravelEgypt)',
    'HONEYMOONERSQUOTATION(ArchersTours-Micky)',
    'HoneymoonSafariandZanzibar(LibetIter-Micky)',
    'HongleiWang(Agustin-SB)',
    'HoudaTazi(Micky-Drct)',
    'HuangShuo(Micky-Drct)',
    'IainMcLachlan(Agustin-Drct)',
    'IanPackwood(Agustin-Drct)',
    'Ilaria(Sultan-Drct)',
    'IlariaMancini(Alex)',
    'IlariaStefanelli(Capri-EleonoraOngaro)',
    'IlariaTonin(Anderson)',
    'IlianaFssl(Micky-SB)',
    'IreneRoccaforte(Alessia)',
    'IrideBoffardi(Roberto)',
    'IrinaMedich(Anderson)',
    'IsaacAguero(Micky-Drct)',
    'IsabellaGiani(Alex)',
    'IsottaScarpa(Alessia)',
    'IvanaTorresan(Nuru)',
    'IvanMartorellil(Sultan-SB)',
    'JacopoMolon(Sultan-Drct)',
    'JacquelineMaglio(Micky-Drct)',
    'JaneZhao(Agustin-SB)',
    'JarenChen(KuoniTumlare-Agustin)',
    'JatinderSingh(Agustin-Drct)',
    'JaymonMcDevitt(Agustin-Drct)',
    'JennyRogers(Micky-SB)',
    'Jeriann(Sultan-Drct)',
    'Jessica(Anderson)',
    'JessicaGarelli(Nuru-Drct)',
    'JessicaRamirez(Agustin-Drct)',
    'JoeDraker(Micky-SB)',
    'JonSalas(Sultan-SB)',
    'Jose(Micky-Drct)',
    'Joyce(Agustin-Drct)',
    'JUL(Sultan-Drct)',
    'JuliaKelly(Anderson)',
    'JuliaSelva(Anderson)',
    'July2026(WOA-Micky)',
    'JussiHolappa(Adele-Drct)',
    'Justin(EncounterAfricaSafari-Micky)',
    'KaitlynChambers(Agustin-Drct)',
    'Karan(BTG-Micky)',
    'KarimeRodriguez(Micky-Drct)',
    'KarstenChetcuti(Micky-Drct)',
    'KatherineBallard(Micky-Drct)',
    'KatieChisholm(Agustin-SB)',
    'KatjaTercelj(Anderson)',
    'Katrina(WOA-Micky)',
    'Kaushal(BTG-Micky)',
    'KavisyaCherukuri(Micky-Drct)',
    'KayKovitprakornkul(Sultan-Drct)',
    'Keezengo(Adele-Drct)',
    'Keezengo(Adele-Drct) - August',
    'Kenya(LaTimpaTravel-PS-Roberto)',
    'KenyaSafari(SonoTravel-Micky)',
    'KeziahCamilleRezaey(Agustin-SB)',
    'Kiboko(Teloni-Roberto)',
    'KibokoBeachAI(Cimoservice-Roberto)',
    'KibokoFlyOutZNZ(UnEmozionePerSempre-PS-Roberto)',
    'KigaliSafari(BTG-Micky)',
    'Kilimanjaro(BTG-Micky)',
    'KimAudette(Agustin-Drct)',
    'KimberlyBills(Sultan-SB)',
    'KirstyEddyl(Sultan-SB)',
    'Kishor(BTG-Micky)',
    'Koom(BTG-Micky)',
    'KUNHSIANGLIN(Agustin-Drct)',
    'KyrieWu(Agustin-SB)',
    'Ladies(WOA-Micky)',
    'LakshmiMorisetti(Agustin-Drct)',
    'Laura(Nuru)',
    'Laura(Sultan-Drct)',
    'LauraBattistini(Alex)',
    'LauraBenedetti(Anderson)',
    'LauraBoschiroli(Anderson)',
    'LauraGenta(Anderson)',
    'LauraJul27(Roberto)',
    'LauraMarta(Alessia)',
    'LauraOlivares',
    'LauraPaoli(Alessia)',
    'LauraPiccinali(Aessia)',
    'LauraPizzi(Federica_Kailas_Alex)',
    'LauraPizzi(HomeandHawayViaggi-Daniela)',
    'LauraPozzi(Sara)',
    'LauraSumner(CaminoYogaRetreats-Sara)',
    'LauraVerardi(Anderson)',
    'Laverda(AvventureEsotiche-PS-Roberto)',
    'LeaPaserman(Rick)',
    'Leon(Samwel-Drct)',
    'LeonardoGiulio(Sultan-Drct)',
    'LeonieReisner(Agustin-Drct)',
    'Leslie(Agustin-Drct)',
    'LetiziaScopelliti(Sultan-Drct)',
    'LiaoZhiyong(Agustin-Drct)',
    'Linda Jorge(Adele-Drct)',
    'LindaCai(Micky-Drct)',
    'LindadiFederico(Sultan-SB)',
    'LindaMussoni(Alessia)',
    'LiPingChen(Agustin-Drct)',
    'LisaCingolani(Anderson)',
    'LisaGramegna(Trafficantidiviaggi-PS-Daniela)',
    'LisaJohnson(Micky-Drct)',
    'LisaMacPherson(Micky-SB)',
    'LisaPaternostei(Anderson)',
    'LisaStrappazzon(Daniela-Drct)',
    'LisbiValdez(Micky-Drct)',
    'LorenzaMazzeo2(Sara)',
    'LorenzoBurgalassi(Daniela)',
    'LorenzoDall\'olio(Nuru-Trekk)',
    'LorenzoLavorgna(Sultan-Drct)',
    'LorenzoLongo(Anderson)',
    'LorenzoScerra(Anderson)',
    'LorenzoVitileia(Sultan-SB)',
    'Luca(Adriana-Roberto)',
    'Luca(Anderson)',
    'Luca(Sultan-Drct)',
    'LucaDandria(Anderson)',
    'LucaRossella(Alessia)',
    'LucasChen(Agustin-Drct)',
    'LucaToselli(Sara)',
    'LucaVertova(Nuru)',
    'LucaVillani(Anderson)',
    'luciacazzato(Sultan-Drct)',
    'LucianaSponsiello(Capri)',
    'LucianoGavoni(Sara)',
    'LuciaVitiello(Sultan-Drct)',
    'LucreziaCastellano(Anderson)',
    'LudmillaXavier(Micky-Drct)',
    'LudovicaCiccone(Roberto)',
    'LudovicaMorvillo(Anderson)',
    'Luigi(Anderson)',
    'LuigiRubagotti(Alessia)',
    'LuisaColantonio(Anderson)',
    'LukeLinton(Sultan-SB)',
    'LuliiaBudnik(Anderson)',
    'Lydia(Sultan-Drct)',
    'Lyle(ExploreUnlimited-Micky)',
    'LyndseySchlegel(Agustin-Drct)',
    'MaddalenadeRosa(Alessia)',
    'MaddalenaMiccio(AuroraViaggi-LAM-Daniela-UGANDA)',
    'Mafia20pax(OceanoPoint-Alex)',
    'MailaPeluncchini(Anderson)',
    'MalakAbusale(Micky-Drct)',
    'Mancuso(HTSViaggi-Daniela)',
    'Mannella(LeAvventurediEnne_Alessia)',
    'ManolaGiannini(Anderson)',
    'Manuela(Nuru)',
    'ManuelaMinghinelli(Capri-EleonoraOngaro)',
    'ManuelTarabusii(Sultan-Drct)',
    'MarcellaN¢brega(Samwel-SB)',
    'MarcellaN¢bregaSouto(Samwel-SB)',
    'March(KendiritaTours-Micky)',
    'March2026(Libetiter-Micky)',
    'MarcoBarone(Anderson)',
    'MarcoBigliano(Capri)',
    'MarcoBotteghi(Anderson)',
    'MarcoBruschi(Nuru-Drct)',
    'MarcoCecchin(Sara)',
    'MarcoChielli(Alessia)',
    'MarcoDaCol(Nuru-Trekk)',
    'MarcoDeCoppi(Oltreilviaggio-PS-Daniela-KENYA)',
    'MarcoDonati(Capri)',
    'MarcoGatti(Alessia)',
    'MarcoGhezzi(Sultan-Drct)',
    'MarcoInnocenti(Nuru-Drct)',
    'MarcoMagnani(Anderson)',
    'MarcoScapellato(Anderson)',
    'MarcoSimion(Anderson)',
    'MargaroliOct2026(VolaEVa-Kenya-Roberto)',
    'Margherita(Micky-Drct)',
    'MargheritaBaraldi(Nuru-Trekk)',
    'Maria(KiwiViaggi-Nuru)',
    'MariaCabianca(Agustin-Drct)',
    'MariaChiaraBonino(Daniela)',
    'MariagraziaPino(Anderson)',
    'MariaGroppi(Nuru)',
    'MariaGuerrieri(Anderson)',
    'MariaMangieri(Nuru-Drct)',
    'MarianaPais(Samwel-SB)',
    'MariannaNicodemo(Sultan-Drct)',
    'MariannaTodeschini(Anderson)',
    'MariaPanico(Anderson)',
    'MariaTeresa(KiwiViaggi(Daniela)',
    'MariaTeresaCalabretti(Alessia)',
    'MariaVittoriaSitti(Anderson)',
    'MaricaTenan(Nuru-Drct)',
    'MariedeMontille(Adele-Drct)',
    'mariefrancoise(Samwel-Drct)',
    'MarielSanna(Nuru-Trekk)',
    'Marina(Micky-Drct)',
    'Marina(WOA-Micky)',
    'MarinaGarcia(Nuru-Drct)',
    'MarinaKrynina(Micky-SB)',
    'MarioHuang(Nuru-Drct)',
    'MaristellaCiliberti(Sara-Drct)',
    'Marta(Sultan-Drct)',
    'MartaBuras(Alessia)',
    'MartaRossi(Alessia)',
    'MartaRossi(Alex)',
    'MartaRossi(Anderson)',
    'MartaValenzano(Nuru)',
    'Martina(Anderson)',
    'MartinaCarle(Sara)',
    'MartinaCarle2(Sara)',
    'MartinaGoglino(Anderson)',
    'MartinaGolemac(GRUPPO_AuroraViaggi-LAM-Daniela)',
    'MartinaPutzolu(Alessia)',
    'MartinaSartori(Capri)',
    'MartineVigier(Adele-Drct)',
    'MartinRasmussen(Agustin-Drct)',
    'Maruzzi(MondoOverland-Daniela)',
    'MarziaLannucci(Anderson)',
    'MarzouqA(Agustin-Drct)',
    'MassimoCarpione(Sultan-Drct)',
    'MassimoGiovannini(Anderson)',
    'Massimo_ViaggiTribali(Alex)',
    'Matassoni(Africando-Daniela)',
    'MatildaSavaSerafin(Alessia)',
    'Matilde(Sultan-Drct)',
    'MatildePero(Capri)',
    'MatildeSaccardi(Anderson)',
    'Matteo(Sultan-Drct)',
    'Matteo2(Sultan-Drct)',
    'MatteoCampomori(Nuru-Tekk)',
    'MatteoComba(Nuru)',
    'MatteoLorenzi(Anderson)',
    'MatteoLucesoli(Nuru-Trek)',
    'MatteoValloni(Anderson)',
    'MatteoZoppi(ASTISrl-PS-Daniela)',
    'MattiaBonanni(Nuru)',
    'MattiaRagaini(Anderson)',
    'MaurizioAlbalustro(Anderson)',
    'MaurizioAmato(Nuru-Drct)',
    'MaurizioIannitti(Nuru)',
    'MaurizioMarigliano(Nuru)',
    'MauroDimartino(Capri)',
    'Max(Agustin-Drct)',
    'Max(SafariADV-Daniela)',
    'MaxFrancone(Anderson)',
    'MaxMarolt(Agustin-Drct)',
    'MAY10PAX(BTG-Micky)',
    'Meghana(BTG-Micky)',
    'MelanieToussaint(Adele-Drct)',
    'Meng-CheLee(Micky-Drct)',
    'MichaelaFischer(Micky-Drct)',
    'MichaelParlascino(Anderson)',
    'MichaelShreves(Agustin-SB)',
    'MichaelSolan(Roberto)',
    'MichelaBaldrati(Sultan-Drct)',
    'MicheleStuder(Micky-Drct)',
    'MicheleTognola(Alex)',
    'MichelleLawson(Sultan-SB)',
    'MicolGabbai(Nuru)',
    'Mig27(Remco-Roberto)',
    'MigJan27(Eko-Roberto)',
    'Migration(Sultan-Drct)',
    'Migration(Sultan-Monica)',
    'Migrazione(Vantaviaggi-PS-Roberto)',
    'MigSep26(ITop-PS-Roberto)',
    'Mihir(BTG-Micky)',
    'MikeCallahan(Agustin-SB)',
    'MikiParty(Sultan-Drct)',
    'MillieVardon(Agustin-SB)',
    'MinHuiFong(Micky-Drct)',
    'MirkoFrezzato(Nuru)',
    'Mitchel(Nuru)',
    'Mithani(TourandTour-PS-Daniela)',
    'MohamedDaadaoui(Micky-SB)',
    'MonicaCorrias(Anderson)',
    'MonicaDiGuglielmo(Anderson)',
    'Monicai(Sultan-Drct)',
    'MonicaRaciti(Anderson)',
    'MonicaValenti(CommendaTour-LAM-Daniela)',
    'MoniqueOonincx(Agustin-Drct)',
    'MorelliRiccardo(Alessia)',
    'MorganRupinski(Samwel-SB)',
    'MortarottiMattia(Alessia)',
    'MoumniBilal(Sultan-SB)',
    'MrJay(BTG-Micky)',
    'MyrnaGabbayParty(Sultan-YeadimTravel)',
    'NadaAdam(TravelEdge-Agustin)',
    'NadineKnupfer(Agustin-Drct)',
    'Nardorianni(LeAvventurediEnne_Alessia)',
    'NatalijaMocevic(Agustin-Drct)',
    'Natasha(Agustin-Drct)',
    'Navina(Agustin-Drct)',
    'NelloColombo(Alessia)',
    'Niccolo(LaGiostraDeiViaggi-PS-Roberto))',
    'NIckson(Sultan-Drct)',
    'NicolaPillitteril(Sultan-SB)',
    'NicolaRampazzo(MamboTravel-PS-Daniela-KENYA)',
    'NicolaTonghini(Rick)',
    'NicoleBertucci(Anderson)',
    'NicoleBorroni(Sara)',
    'NicoleNg(Sultan-SB)',
    'NicoloBrandi(Capri)',
    'NimishManojShah(VacationsQuest-Micky)',
    'NinoGinardi(Sara)',
    'NiveRaviarunan(Agustin-Drct)',
    'NivesZanini(Sultan-Drct)',
    'Nookda(Micky-Drct)',
    'NorahTang(Micky-Drct)',
    'Novelli(Etnia-Roberto)',
    'NunziaDiFranco(Roberto)',
    'NunziaFalco(Anderson-Drct)',
    'NuriaXiol(Agustin-Drct)',
    'NyerereBeach(OceanoPoint-Roberto)',
    'Obabaluba(MapoWorld-LAM-Daniela)',
    'OlgaBalboa(Agustin-SB)',
    'OliviaMeister(Sultan-SB)',
    'OlivieroCini(Astisrl-PS-Daniela-SUDAFRICA)',
    'PackageSerengetiZanzibar(BTG-Micky)',
    'PamelaLang(Agustin-Drct)',
    'Paola(Sultan-Drct)',
    'PaolaCardilor(Anderson)',
    'PaolaCardilori(Anderson)',
    'PaolaChesler(Anderson)',
    'PaolaErba(Capri-EleonoraOngaro)',
    'PaolaGaz(Nuru-Drct)',
    'PaolaMarangi(Sultan-Drct)',
    'PaolaPonticelli(Anderson)',
    'PaoloCampolonghi(Sultan-Drct)',
    'PaoloCioni(Alessia)',
    'PaoloCordiano(Roberto)',
    'PaoloGalluzzi(Anderson)',
    'PaoloGhidotti(Micky-Drct)',
    'PaoloMaccanti(AstiSrl-PS-Daniela-KENYA)',
    'PaoloRipamonti(Esquire-PS-Roberto)',
    'PaoloZagni(Capri)',
    'PAPAnnemasse(Adele-Drct)',
    'PAPAnnemassebis(Adele-Drct)',
    'PAPVoiron(Adele-Drct)',
    'Parth(BTG-Micky)',
    'PatriciaCohen(Micky-Drct)',
    'PatriziaCaviglia(Capri)',
    'PatriziaPizzotti(Anderson)',
    'PatrizioSisti(NewcoAgency-PS-Daniela-UGANDA)',
    'Paula(Micky-Drct)',
    'PaulMotto(WOA-Micky)',
    'PavelCaizl(Micky-Drct)',
    'PayaDehghani(Sultan-Drct)',
    'Pecar(AuroraViaggi-Lam-Daniela-KENYA)',
    'PeeyushMittal(Sultan-Drct)',
    'PeonardoPerini(Nuru-Drct)',
    'Pepe(MapoWorld-LAM-Daniela)',
    'PeterV(Agustin-Drct)',
    'PiaDell\'imperio(Nuru-Drct)',
    'Pierangela(Nuru)',
    'PierpaoloGoffredo(Teloni-Roberto)',
    'PierreAldoPoretti(Anderson)',
    'PietroGabbuti(Nuru-Drct)',
    'PietroRaffa(Roberto)',
    'PietroStampella(Sultan-Drct)',
    'Pontieri(Oniva-Roberto)',
    'PrinitaBaijnath(Agustin-SB)',
    'PriscillaTrivisonne(HTSViaggi-Daniela)',
    'PrivateSafariandRelaxBeach(LibetIterTravel-Micky)',
    'Priyanka(Micky-Drct)',
    'Propose(Libetiter-Micky)',
    'PumbaBeach(CTC-Roberto)',
    'PumbaSpec(BolleDAcqua-Roberto)',
    'PumbaSpecial(Eko-Roberto)',
    'PumbaZNZ(Gate65-Roberto)',
    'QiuhaoHuang(Agustin-Drct)',
    'Queenie(Micky-Drct)',
    'RabiyaZaman(Micky-Drct)',
    'RacheleDesiato(Sultan-Drct)',
    'RacheleDiVita(Anderson)',
    'RaffaelaDiPace(Micky-Drct)',
    'Raffaele(Nuru-Trekk)',
    'RaffaeleSglavo(Nuru)',
    'RaffaellaCodino(Roberto)',
    'RaffaellaDeRentiis(Nuru)',
    'RaffaellaPicone(Anderson)',
    'RaffaellaSeraglini(ASTI-PS-Roberto)',
    'Rainoldi(Maxtravel-Roberto)',
    'Rajesh(BTG-Micky)',
    'RajKhatri(Sultan-Drct)',
    'RakheeDhiman(Sultan-Drct)',
    'Ramazzotti(Lamiafrica-Roberto)',
    'RaymondLau(Agustin-SB)',
    'Rebecca(Sultan-Drct)',
    'RebeccaBecheroni(Anderson)',
    'ReginaMaria(Sultan-Drct)',
    'RianDondero(Sultan-SB)',
    'Riccardo(Sultan-Drct)',
    'RiccardoBaronti(Alessia)',
    'RiccardoCampagnol(Alex)',
    'RiccardoCampagnoli(Alex)',
    'RiccardoCanuto(Capri)',
    'RiccardoCoatti(MaurizioScafuro-Daniela-KENYA)',
    'RiccardoDrive(Capri)',
    'RiccardoGallottini(Nuru-Drct)',
    'RiccardoOliviero(Anderson)',
    'RiccardoPasotti(FedericaKailas_Alex)',
    'RiccardoPatera(Anderson)',
    'RiccardoSindoni(Sultan-Drct)',
    'RIck',
    'Rita(Agustin-Drct)',
    'Ritesh(BTG-Micky)',
    'Roberta(Sultan-Drct)',
    'RobertaCereda(Nuru-Drct)',
    'RobertaChiudinelli(Anderson)',
    'RobertaColbrelli(Sultan-Drct)',
    'RobertaE(Sultan-Drct)',
    'RobertaMarchi(BeNomad-Roberto)',
    'RobertaPenzo(Nomadoos-Daniela)',
    'RobertaVerdecchi(Anderson)',
    'Roberto(LifeViaggi-Daniela-KENYA)',
    'RobertoAffini(Daniela-PROVA)',
    'RobertoCapocchi(AstiSrl-PS-Daniela-KENYA)',
    'RobertoCorazzi(Anderson)',
    'RobertoGaveglio(Diamante-PS-Roberto)',
    'RobertoNilo(Anderson)',
    'RobertoNofri(Alessia)',
    'RobertoRaffaeli(Anderson)',
    'RoisinMcMahon(Samwel-SB)',
    'RosannaMonopoli(Roberto)',
    'RosaVespoli(Rick)',
    'RossanoFlavianelli(Anderson)',
    'Rossella(Sultan-Drct)',
    'Roy(Micky-Drct)',
    'Ruggero(Anderson)',
    'RuggeroZecchin(Alessia)',
    'RummyBajwa(Micky-SB)',
    'Rungpatch2026(SagaExpeditions-Micky)',
    'RupeshRane(Micky-Drct)',
    'RustjaMitja(AuroraViaggi-LAM-Daniela-KENYA)',
    'SabinaPruitiCiarello(Anderson)',
    'SabrinaSelva(Capri-EleonoraOngaro)',
    'SabrinsSpampinato(Nuru-Drct)',
    'SadiaThantrey(Agustin-Drct)',
    'SafariPackage(LibetIterTravel-Micky)',
    'SafariPackage2026(LibetIterTravel-Micky)',
    'SafariPemba(Verticalife-Roberto)',
    'SafariQuoteRequest(LibetIter-Micky)',
    'SafariTrip(WOA-Micky)',
    'SafwaElsayed(Micky-Drct)',
    'Sajid(BTG-Micky)',
    'SaloniDesai(Sultan-Drct)',
    'SalvatoreBoccia(Capri)',
    'SamanthaPellizzari(Sultan-Drct)',
    'SamNorling(Agustin-SB)',
    'SamueleBaldo(Sultan-Drct)',
    'SamueleOddo(Sara)',
    'SanaFarooqui(Micky-Drct)',
    'Sander(Micky-Drct)',
    'Sandy(Agustin-Drct)',
    'Sara(Nuru-Drct)',
    'Sara(Nuru-Trek)',
    'SaraBurnett(Samwel-SB)',
    'SaraCampagnola(Alessia)',
    'SaraGreffi(Nuru-Trekk)',
    'SaraMarcolla(Capri)',
    'SaraMbesi(Anderson)',
    'SaraMilia(Nuru-Trekk)',
    'SaraRicci(Anderson)',
    'SaraRick',
    'SaraSansaro(Anderson)',
    'SarveshMathi(Micky-Drct)',
    'SaskiaFichera(Daniela)',
    'ScottCirillo(Agustin-Drct)',
    'ScottEdwards(Micky-SB)',
    'SeanYuxiaoZhou(Agustin-Drct)',
    'SebastianHurtado(Micky-SB)',
    'Sebastiano(Nuru-Trekk)',
    'September(SOCOTRAtoursandtravel-Micky)',
    'September(VacationsQuest-Micky)',
    'September2026(Kendirita-Micky)',
    'SerenaBettarelli(Anderson)',
    'SerenaGismundi(Roberto)',
    'Serengeti(Sultan-Drct)',
    'SerengetiFlyIn(GoWorld-Roberto)',
    'SERENGETIZANZIBAR(BTG-Micky)',
    'SergioGalimberti(Sara)',
    'Shah(BTG-Micky)',
    'ShannonDeSilvia(Agustin-Drct)',
    'Sharan(Sultan-Drct)',
    'SheilaCunha(Sultan-SB)',
    'ShengjiChen(Micky-Drct)',
    'Shirish(Sultan-Drct)',
    'ShivangiTibrewala(Sultan-Drct)',
    'ShrenikaChopda(Sultan-Drct)',
    'SilvanoSignorini(Alessia-Drct)',
    'Silvia(Sultan-Drct)',
    'SilviaAndriotto(FulviaTour-Roberto)',
    'SilviaDiPilato(Nuru)',
    'SilviaFerraresi(Roberto)',
    'SilviaLisanti(Sultan-Drct)',
    'SilviaSequi(Sultan-Drct)',
    'SilviaSilvagni(Alex)',
    'SilviaToncelli(Anderson)',
    'SilviaVanni(Anderson)',
    'sima(Sultan-Yeadimtravel)',
    'Simba(ShadowTravel-Roberto)',
    'SImba(Sultan-Drct)',
    'Simba3(Tenere-Roberto)',
    'Simba3Lux(GoWorld-Roberto)',
    'SimbaBeach(DecioViaggi-PS-Roberto)',
    'SimbaBeach(Viaggiamondo-Roberto)',
    'Simona(VerticalLife-PS-Daniela-KENYA)',
    'SimonCampani(Anderson)',
    'Simone(Sultan-Drct)',
    'SimoneCirigliano(Nuru-Drct)',
    'SimoneDiNicuolo(Sara)',
    'SimoneLucaGaio(Capri)',
    'SimoneRomano(Anderson)',
    'SimpleSafariandZanzibar(Libetiter-Micky)',
    'SiViaggiare(GoWorld-Roberto)',
    'SlawomirSteinborn(Sultan-Drct)',
    'Sneha(BTG-Micky)',
    'SofiaCiammetti(Nuru)',
    'SofiaGinetti(Anderson)',
    'Sohli(DimensioneAvventura-Daniela)',
    'SongboXu(Agustin-Drct)',
    'SoniaEdie(Anderson)',
    'SonjaRampello(Anderson)',
    'Sothernsafari(KendiritaTours-Micky)',
    'SouriTrip(Caniato)Alessia',
    'SpecialRequirement(BTG-Micky)',
    'StaciOshea(Samwel-SB)',
    'StefanCrosa(Daniela)',
    'StefanelliMonica(Sultan-Drct)',
    'StefaniaCoscarella(Anderson)',
    'StefaniaCoscarella(Anderson-Drct)',
    'StefaniaLaManna(Rick)',
    'StefaniaLerro(Anderson)',
    'StefaniaLupica(Daniela-KENYA)',
    'StefaniaMarini(Sara)',
    'StefaniaMarini2(Sara)',
    'StefaniaPatt(Anderson)',
    'StefaniaPozzoli(Anderson)',
    'StefaniaSicuso(Roberto)',
    'StefaniaStacchiotti(Anderson)',
    'StefaniaTorre(Anderson)',
    'Stefano(Nuru-Drct)',
    'StefanoBuccella(Sara)',
    'StefanoColicchio(TVT-PS-Roberto)',
    'StefanoFissolo(Capri)',
    'StefanoFrancescato(Rick)',
    'StefanoMannini(Sultan-Drct)',
    'StefanoTodde(LastminuteTour-Daniela-KENYA)',
    'StellaSun(Agustin-Drct)',
    'StephaniePoon(Agustin-SB)',
    'SudheerTekumalla(Sultan-Drct)',
    'Suhaib(BTG-Micky)',
    'SunandiniSingh(BTG-Micky)',
    'SuparnaMundodi(Sultan-SB)',
    'SurecaVenter(Samwel-SB)',
    'Susana(Sultan-Drct)',
    'SuzanadeBoni(Agustin-SB)',
    'SuzanaMachado(Sultan-Drct)',
    'SuzieLiu(Agustin-Drct)',
    'SV2809(SartiViaggisti-Roberto)',
    'SwamyYeles(Agustin-Drct)',
    'Talamo(Africando-Daniela)',
    'Tanaz(BTG-Micky)',
    'Tanja(Sultan-Drct)',
    'Tanzania(CondorTravel-Roberto)',
    'TanzaniaPart(SonoTravel-Micky)',
    'TanzaniaQuery(BTG-Micky)',
    'TanzaniaSafariQuery(LuxuryUnlimited-Micky)',
    'TanzaniaZanzibar(Libetiter-Micky)',
    'TDP(TerreDiPianura-Roberto)',
    'TemboBeach(AntologiaViaggi-Roberto)',
    'TemboPemba(Daver-PS-Roberto)',
    'Tess(Agustin-Drct)',
    'Thomas(EncounterAfricaSafaris-Micky)',
    'Thomas(Sultan-Drct)',
    'ThongLeHoang(Agustin-Drct)',
    'TianchenDu(Agustin-Drct)',
    'TifanyX(Micky-Drct)',
    'TilHanika(Agustin-Drct)',
    'TimAtkinson(Sultan-SB)',
    'TimMurch(Agustin-Drct)',
    'TizianoFalcone(Anderson)',
    'TobiaKessler(Rick)',
    'TobiasKessler(Rick)',
    'TommasoCalvelli(Alessia)',
    'TommasoCasolla(MZTravel-Daniela)',
    'TommasoNigroi(Anderson)',
    'TommasoSantapaola(Nuru)',
    'TommasoTeti(Agustin-Drct)',
    'TommievanKouteren(Micky-SB)',
    'Tourbante(GoWorld-Roberto)',
    'TravelWithUs(GoWorld-Roberto)',
    'TrekPumba(Oniva-Roberto)',
    'TristaNabors(Micky-Drct)',
    'TzKe(Matthew-Micky)',
    'TzZanzibar(WOA-Micky)',
    'UlrikeZeitlinger-Haake(Sultan-SB)',
    'Umberto(Nuru-Trekk)',
    'UrgentQuery(BTG-Micky)',
    'UrielAsh(Micky-SB)',
    'ValentinaDini(ASTI-PS-Roberto)',
    'ValentinaHering(Anderson)',
    'ValentinaMaiorana(Anderson)',
    'ValentinaMazzuca(Alex)',
    'ValentinaRuscigno(Sara)',
    'ValentinaSerafini(Sultan-Drct)',
    'ValentinaTroiani(Anderson)',
    'ValentinaVitali(Alessia)',
    'ValentinaZantomio(AVIT-Daniela-KENYA)',
    'ValeriaCaporaletti(Anderson)',
    'ValeriaFacchin(Anderson)',
    'ValeriaTranzilloo(Anderson)',
    'ValeriaVilla(Anderson)',
    'ValerieTeson(Samwel-SB)',
    'ValerioGiannelli(Anderson)',
    'ValerioMessina(Anderson)',
    'Vali(Alessia)',
    'ValleriaCollati(Nuru-Drct)',
    'VanessaDelCurto(Alex)',
    'VanessaLu(Micky-Drct)',
    'Varunx(BTG-Micky)',
    'VentimigliaRossella(Alessia)',
    'VeraWeber(Agustin-Drct)',
    'VerenaAicher(Agustin-Drct)',
    'Veronica(Areatour)_Alessia',
    'VeronicaFalcionelli(Sultan-Drct)',
    'VeronicaFarruggia(Capri)',
    'VeronicaGelli(Daniela)',
    'VeronicaSalas(Sultan-SB)',
    'VeronicaVelloni(Nuru-Tekk)',
    'Vinay(BTG-Micky)',
    'Vincenzo(Salutida-Daniela-SUDAFRICA)',
    'VincenzoMarzullo(Anderson)',
    'VincenzoSavarino(Anderson)',
    'VincenzoSavarino(Anderson) - Copy',
    'VincenzZinsinger(Micky-Drct)',
    'ViolaDiBlasio(Anderson)',
    'Virginia(Anderson)',
    'VirginiaZappulla(Alessia)',
    'VitoDiPinto(Anderson)',
    'VittorioPieroBonfante(RemcoViaggi-Daniela-UGANDA)',
    'Viviana(Nuru)',
    'VoyagesChabanne(Adele-Drct)',
    'Vukic(TourAndTour-Roberto)',
    'WinkyChua(Agustin-Drct)',
    'XiaoHan(Agustin-Drct)',
    'XiaoyanGuo(Agustin-Drct)',
    'XingyueWang(Sultan-SB)',
    'YangMorten(Agustin-Drct)',
    'YanMeg(Agustin-Drct)',
    'YaoMu(Agustin-SB)',
    'Yara(Agustin-Drct)',
    'YolandaShen(Agustin-Drct)',
    'YuKang(Agustin-SB)',
    'YuleSun(Agustin-Drct)',
    'YuXia(Agustin-SB)',
    'Zagheni(SouriTrip-Roberto)',
    'ZanzibarPackage(BTG-Micky)',
    'ZanzibarSafari(WOA-Micky)',
    'ZhaoyinJiang(Agustin-SB)',
    'ZhengziYi(Agustin-Drct)',
    'ZiyangChen(Micky-Drct)',
    'ZNZ(TheTravelFamily-Roberto)',
    'ZNZDuma(ASTI-PS-Roberto)',
    'ZNZDuma(Etnia-Roberto)',
    'ZNZDumaShort(CambioRotta-PS-Roberto)',
    'ZnzSafari(FarEast-Samwel)',
    'ZT0302(Zucchitours-PS-Roberto)',
];
// ── Helpers ───────────────────────────────────────────────────────────────────
function norm(string $s): string {
    return strtolower(preg_replace('/[^a-z0-9]/i', '', $s));
}

/** Extract the customer-name part of a folder (everything before first '('). */
function folderCustomer(string $folder): string {
    return preg_replace('/\(.*$/', '', $folder);
}

/**
 * Return all folders that match a customer name.
 * Returns array of ['folder'=>..., 'quality'=>'exact'|'starts'|'contains']
 */
function findMatches(string $customerName, array $folders): array {
    $needle = norm($customerName);
    if (strlen($needle) < 3) return [];
    $results = [];
    foreach ($folders as $folder) {
        $hay = norm(folderCustomer($folder));
        if ($hay === $needle) {
            $results[] = ['folder' => $folder, 'quality' => 'exact'];
        } elseif (strlen($needle) >= 5 && str_starts_with($hay, $needle)) {
            $results[] = ['folder' => $folder, 'quality' => 'starts'];
        } elseif (strlen($needle) >= 5 && str_contains($hay, $needle)) {
            $results[] = ['folder' => $folder, 'quality' => 'contains'];
        }
    }
    return $results;
}

// ── Handle POST (apply selected matches) ─────────────────────────────────────
$applyLog = [];
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['apply'])) {
    $db   = db();
    $stmt = $db->prepare("UPDATE requests SET practice_code = ? WHERE id = ? AND (practice_code IS NULL OR practice_code = '')");
    foreach ($_POST['match'] ?? [] as $id => $folder) {
        $folder = trim($folder);
        if ($folder === '') continue;
        $stmt->execute([$folder, (int)$id]);
        $applyLog[(int)$id] = $folder;
    }
}

// ── Load unmatched requests ───────────────────────────────────────────────────
$db   = db();
$rows = $db->query(
    "SELECT id, customer_name, date_received, agent_id, status
     FROM requests
     WHERE status = 'Inquiry'
       AND (practice_code IS NULL OR practice_code = '')
     ORDER BY date_received DESC"
)->fetchAll(PDO::FETCH_ASSOC);

// ── Build match candidates ────────────────────────────────────────────────────
$candidates = [];
foreach ($rows as $row) {
    $matches = findMatches($row['customer_name'], $folders2026);
    $candidates[] = [
        'row'     => $row,
        'matches' => $matches,
    ];
}
$withMatch    = array_filter($candidates, fn($c) => count($c['matches']) > 0);
$withoutMatch = array_filter($candidates, fn($c) => count($c['matches']) === 0);

?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Backfill practice_code — 2026</title>
<style>
body { font-family: Arial, sans-serif; font-size: 13px; margin: 20px; background:#f5f5f5; }
h1 { color: #C0211B; }
h2 { margin-top: 28px; border-bottom: 2px solid #ddd; padding-bottom: 6px; }
table { border-collapse: collapse; width: 100%; background: #fff; margin-bottom: 20px; }
th { background: #C0211B; color: #fff; padding: 8px 10px; text-align: left; }
td { padding: 7px 10px; border-bottom: 1px solid #eee; vertical-align: top; }
tr:hover td { background: #fafafa; }
.exact    { color: #1a6b3a; font-weight: bold; }
.starts   { color: #e87722; }
.contains { color: #888; }
.ambiguous { background: #fff8e1 !important; }
.no-match  { color: #999; font-style: italic; }
.badge { display:inline-block; padding:2px 7px; border-radius:10px; font-size:11px; font-weight:bold; }
.b-exact    { background:#d6edd9; color:#1a6b3a; }
.b-starts   { background:#fef0e5; color:#e87722; }
.b-contains { background:#eee;    color:#666;    }
.b-ambig    { background:#fff3cd; color:#856404; }
select { width: 100%; padding: 4px; border: 1px solid #ccc; border-radius:4px; }
.btn-apply { background:#C0211B; color:#fff; border:none; padding:10px 28px; font-size:14px; border-radius:6px; cursor:pointer; margin-top:16px; }
.btn-apply:hover { background:#a01a14; }
.log-ok { background:#d6edd9; padding:10px; border-radius:6px; margin-bottom:16px; }
.stats { background:#fff; padding:14px; border-radius:8px; margin-bottom:20px; display:flex; gap:24px; }
.stat { text-align:center; }
.stat-n { font-size:28px; font-weight:bold; color:#C0211B; }
.stat-l { font-size:12px; color:#888; }
</style>
</head>
<body>
<h1>🗂 Backfill practice_code from 2026 Dropbox folders</h1>

<?php if ($applyLog): ?>
<div class="log-ok">
    ✅ Updated <strong><?= count($applyLog) ?></strong> request(s):<br>
    <?php foreach ($applyLog as $id => $f): ?>
        &nbsp; • id=<?= $id ?> → <code><?= htmlspecialchars($f) ?></code><br>
    <?php endforeach; ?>
</div>
<?php endif; ?>

<div class="stats">
    <div class="stat"><div class="stat-n"><?= count($rows) ?></div><div class="stat-l">Inquiry with no folder</div></div>
    <div class="stat"><div class="stat-n"><?= count($withMatch) ?></div><div class="stat-l">Matches found</div></div>
    <div class="stat"><div class="stat-n"><?= count($withoutMatch) ?></div><div class="stat-l">No match</div></div>
    <div class="stat"><div class="stat-n"><?= count($folders2026) ?></div><div class="stat-l">2026 folders</div></div>
</div>

<?php if (count($withMatch) > 0): ?>
<form method="POST">
<h2>✅ Requests with matches (<?= count($withMatch) ?>)</h2>
<p>Review the suggestions, adjust the dropdown if needed, uncheck any you want to skip, then click Apply.</p>
<table>
    <tr>
        <th style="width:36px">✓</th>
        <th>ID</th>
        <th>Customer name</th>
        <th>Date</th>
        <th>Suggested folder</th>
        <th>Quality</th>
    </tr>
    <?php foreach ($withMatch as $c):
        $row     = $c['row'];
        $matches = $c['matches'];
        $best    = $matches[0];
        $isAmbig = count($matches) > 1;
        $rowClass = $isAmbig ? ' class="ambiguous"' : '';
    ?>
    <tr<?= $rowClass ?>>
        <td><input type="checkbox" name="apply_<?= $row['id'] ?>"
                   id="cb_<?= $row['id'] ?>"
                   <?= $isAmbig ? '' : 'checked' ?>
                   onchange="toggleSelect(<?= $row['id'] ?>)"></td>
        <td><?= $row['id'] ?></td>
        <td><strong><?= htmlspecialchars($row['customer_name']) ?></strong></td>
        <td><?= $row['date_received'] ?></td>
        <td>
            <?php if ($isAmbig): ?>
            <select name="match[<?= $row['id'] ?>]" id="sel_<?= $row['id'] ?>">
                <?php foreach ($matches as $m): ?>
                <option value="<?= htmlspecialchars($m['folder']) ?>"
                    class="<?= $m['quality'] ?>">
                    <?= htmlspecialchars($m['folder']) ?>
                </option>
                <?php endforeach; ?>
            </select>
            <?php else: ?>
            <input type="hidden" name="match[<?= $row['id'] ?>]"
                   value="<?= htmlspecialchars($best['folder']) ?>">
            <code><?= htmlspecialchars($best['folder']) ?></code>
            <?php endif; ?>
        </td>
        <td>
            <?php if ($isAmbig): ?>
                <span class="badge b-ambig">⚠ <?= count($matches) ?> matches</span>
            <?php else: ?>
                <span class="badge b-<?= $best['quality'] ?>"><?= $best['quality'] ?></span>
            <?php endif; ?>
        </td>
    </tr>
    <?php endforeach; ?>
</table>
<button type="submit" name="apply" value="1" class="btn-apply">
    Apply selected updates
</button>
</form>
<?php endif; ?>

<?php if (count($withoutMatch) > 0): ?>
<h2>❌ No match found (<?= count($withoutMatch) ?>)</h2>
<table>
    <tr><th>ID</th><th>Customer name</th><th>Date</th><th>Status</th></tr>
    <?php foreach ($withoutMatch as $c): $row = $c['row']; ?>
    <tr>
        <td><?= $row['id'] ?></td>
        <td><?= htmlspecialchars($row['customer_name']) ?></td>
        <td><?= $row['date_received'] ?></td>
        <td><?= htmlspecialchars($row['status']) ?></td>
    </tr>
    <?php endforeach; ?>
</table>
<?php endif; ?>

<script>
function toggleSelect(id) {
    const cb  = document.getElementById('cb_'  + id);
    const sel = document.getElementById('sel_' + id);
    if (sel) sel.disabled = !cb.checked;
}
// Disable selects for unchecked ambiguous rows on load
document.querySelectorAll('input[type=checkbox]').forEach(cb => {
    const id  = cb.id.replace('cb_','');
    const sel = document.getElementById('sel_' + id);
    if (sel) sel.disabled = !cb.checked;
});
</script>
</body>
</html>
